# Generated by Django 6.1 on 2026-08-16 18:46

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityLandingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(max_length=255)),
                ('hero_subtitle', models.TextField(blank=True)),
                ('default_city', models.CharField(blank=True, help_text='City name to pre-filter listings e.g. New Delhi', max_length=100)),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Text shown above listings')),
                ('about', wagtail.fields.RichTextField(blank=True, help_text='About section below listings')),
                ('seo_title_override', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.TextField(blank=True, max_length=300)),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'City Landing Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CityFAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', wagtail.fields.RichTextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_faqs', to='landing.citylandingpage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', wagtail.fields.RichTextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='wagtailcore.page')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentLandingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(max_length=255)),
                ('hero_subtitle', models.TextField(blank=True)),
                ('default_treatment_slug', models.CharField(blank=True, help_text='Treatment slug to pre-filter listings e.g. alcohol-addiction', max_length=100)),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('about', wagtail.fields.RichTextField(blank=True)),
                ('seo_title_override', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.TextField(blank=True, max_length=300)),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Treatment Landing Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TreatmentFAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', wagtail.fields.RichTextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_faqs', to='landing.treatmentlandingpage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
