# Generated by Django 6.1 on 2026-09-11 18:06

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citylandingpage',
            name='about',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='citylandingpage',
            name='default_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='citylandingpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='treatmentlandingpage',
            name='default_treatment_slug',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
