# Generated by Django 6.1 on 2026-09-11 19:03

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_alter_citylandingpage_about_and_more'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOLandingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(max_length=255)),
                ('hero_subtitle', models.TextField(blank=True)),
                ('hero_left_text', wagtail.fields.RichTextField(blank=True, help_text='Rich text shown on left side of hero')),
                ('hero_badge_1', models.CharField(blank=True, help_text='e.g. Expert Reviewed', max_length=100)),
                ('hero_badge_2', models.CharField(blank=True, help_text='e.g. Updated for 2026', max_length=100)),
                ('hero_badge_3', models.CharField(blank=True, help_text='e.g. Verified Information', max_length=100)),
                ('hero_badge_4', models.CharField(blank=True, help_text='e.g. 100% Confidential', max_length=100)),
                ('intro_text', wagtail.fields.RichTextField(blank=True, help_text='Text section below hero')),
                ('section_1_title', models.CharField(blank=True, max_length=255)),
                ('section_1_content', wagtail.fields.RichTextField(blank=True)),
                ('section_2_title', models.CharField(blank=True, max_length=255)),
                ('section_2_content', wagtail.fields.RichTextField(blank=True)),
                ('section_3_title', models.CharField(blank=True, max_length=255)),
                ('section_3_content', wagtail.fields.RichTextField(blank=True)),
                ('section_4_title', models.CharField(blank=True, max_length=255)),
                ('section_4_content', wagtail.fields.RichTextField(blank=True)),
                ('section_5_title', models.CharField(blank=True, max_length=255)),
                ('section_5_content', wagtail.fields.RichTextField(blank=True)),
                ('listing_section_title', models.CharField(default='Top Rehabs', help_text='Heading above the rehab listings e.g. Top Rehabs for Alcohol Addiction in Delhi', max_length=255)),
                ('selected_rehab_ids', models.JSONField(blank=True, default=list, help_text='List of RehabCenter IDs to display. Add IDs from Django admin.')),
                ('bottom_section_1_title', models.CharField(blank=True, max_length=255)),
                ('bottom_section_1_content', wagtail.fields.RichTextField(blank=True)),
                ('bottom_section_2_title', models.CharField(blank=True, max_length=255)),
                ('bottom_section_2_content', wagtail.fields.RichTextField(blank=True)),
                ('bottom_section_3_title', models.CharField(blank=True, max_length=255)),
                ('bottom_section_3_content', wagtail.fields.RichTextField(blank=True)),
                ('final_thoughts_title', models.CharField(blank=True, max_length=255)),
                ('final_thoughts_content', wagtail.fields.RichTextField(blank=True)),
                ('seo_title_override', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.TextField(blank=True, max_length=300)),
                ('hero_image', models.ForeignKey(blank=True, help_text='Image shown on right side of hero', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'SEO Landing Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SEOLandingFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', wagtail.fields.RichTextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_faqs', to='landing.seolandingpage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
