# Generated by Django 6.1 on 2026-08-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rehabcentertreatment',
            name='center',
        ),
        migrations.RemoveField(
            model_name='rehabcentertreatment',
            name='treatment',
        ),
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name_plural': 'Amenities'},
        ),
        migrations.AlterModelOptions(
            name='treatmenttype',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AddField(
            model_name='rehabcenter',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='centers', to='listings.amenity'),
        ),
        migrations.AddField(
            model_name='rehabcenter',
            name='category',
            field=models.CharField(blank=True, choices=[('luxury-wellness', 'Luxury Wellness Retreat'), ('luxury-clinical', 'Luxury Clinical Rehab'), ('budget-clinical', 'Budget Clinical Rehab')], max_length=20),
        ),
        migrations.AddField(
            model_name='rehabcenter',
            name='languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='rehabcenter',
            name='patient_profiles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='rehabcenter',
            name='surrounding',
            field=models.CharField(blank=True, choices=[('mountains', 'Mountains'), ('beach', 'Beach'), ('farm', 'Farm/Garden'), ('forest', 'Forest'), ('city', 'City'), ('lake', 'Lake/Riverside')], max_length=20),
        ),
        migrations.AddField(
            model_name='rehabcenter',
            name='treatment_types',
            field=models.ManyToManyField(blank=True, related_name='centers', to='listings.treatmenttype'),
        ),
        migrations.AddField(
            model_name='treatmenttype',
            name='category',
            field=models.CharField(choices=[('adults', 'Adults'), ('child', 'Child & Adolescents'), ('geriatric', 'Geriatric (Elderly)'), ('others', 'Others')], default='adults', max_length=20),
        ),
        migrations.AlterField(
            model_name='rehabcenter',
            name='gender',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('both', 'Men and Women')], default='both', max_length=10),
        ),
        migrations.AlterField(
            model_name='rehabcenter',
            name='price_range',
            field=models.CharField(blank=True, choices=[('lt2', 'Less than 2 Lakhs'), ('2to3', '2-3 Lakhs'), ('3to4', '3-4 Lakhs'), ('4to5', '4-5 Lakhs'), ('gt5', '5+ Lakhs')], max_length=10),
        ),
        migrations.DeleteModel(
            name='RehabCenterAmenity',
        ),
        migrations.DeleteModel(
            name='RehabCenterTreatment',
        ),
    ]
