# Generated by Django 6.1 on 2026-08-17 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_remove_rehabcentertreatment_center_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rehabcenter',
            name='center_facilities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='rehabcenter',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, help_text='e.g. 15', null=True),
        ),
        migrations.AddField(
            model_name='rehabcenter',
            name='in_room_facilities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='rehabcenter',
            name='min_program_duration',
            field=models.CharField(blank=True, help_text='e.g. 14 Days', max_length=50),
        ),
        migrations.AddField(
            model_name='rehabcenter',
            name='recreational_activities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='rehabcenter',
            name='therapies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='rehabcenter',
            name='total_beds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rehabcenter',
            name='total_rooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rehabcenter',
            name='videos',
            field=models.JSONField(blank=True, default=list, help_text='List of video URLs or YouTube embed URLs'),
        ),
        migrations.CreateModel(
            name='RehabCenterAboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_sections', to='listings.rehabcenter')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RehabCenterTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(help_text='e.g. Sr. Psychiatrist & Co-Founder', max_length=255)),
                ('qualification', models.CharField(blank=True, help_text='e.g. M.B.B.S, MD', max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='listings.rehabcenter')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
