# Generated by Django 6.1 on 2026-09-11 18:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_rehabcenter_center_facilities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rehabcenter',
            name='category',
        ),
        migrations.RemoveField(
            model_name='rehabcenter',
            name='description',
        ),
        migrations.RemoveField(
            model_name='rehabcenter',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='rehabcenter',
            name='min_program_duration',
        ),
        migrations.RemoveField(
            model_name='rehabcenter',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='rehabcenter',
            name='surrounding',
        ),
        migrations.RemoveField(
            model_name='rehabcenter',
            name='total_beds',
        ),
        migrations.RemoveField(
            model_name='rehabcenter',
            name='total_rooms',
        ),
        migrations.AddField(
            model_name='rehabcenter',
            name='about',
            field=models.TextField(blank=True, default='', help_text='Minimum 300 words, Maximum 600 words', validators=[django.core.validators.MinLengthValidator(300)], verbose_name='About (300-600 words)'),
        ),
        migrations.AddField(
            model_name='rehabcenter',
            name='activities',
            field=models.JSONField(blank=True, default=list, verbose_name='Activities'),
        ),
        migrations.AddField(
            model_name='rehabcenter',
            name='centre_type',
            field=models.CharField(default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='rehabcenter',
            name='certified_from',
            field=models.CharField(blank=True, max_length=255, verbose_name='Certified From (Optional)'),
        ),
        migrations.AddField(
            model_name='rehabcenter',
            name='district',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='District Name'),
        ),
        migrations.AddField(
            model_name='rehabcenter',
            name='main_facilities',
            field=models.JSONField(blank=True, default=list, verbose_name='Main Facilities'),
        ),
        migrations.AddField(
            model_name='rehabcenter',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Mobile No'),
        ),
        migrations.AddField(
            model_name='rehabcenter',
            name='mobile_alternate',
            field=models.CharField(blank=True, max_length=20, verbose_name='Mobile No (Alternate)'),
        ),
        migrations.AddField(
            model_name='rehabcenter',
            name='occupancy',
            field=models.CharField(blank=True, max_length=100, verbose_name='Occupancy (e.g. 24 Beds)'),
        ),
        migrations.AddField(
            model_name='rehabcenter',
            name='program_duration_max',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Program Duration Max (days)'),
        ),
        migrations.AddField(
            model_name='rehabcenter',
            name='program_duration_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Program Duration Min (days)'),
        ),
        migrations.AddField(
            model_name='rehabcenter',
            name='surroundings',
            field=models.JSONField(blank=True, default=list, verbose_name='Surroundings'),
        ),
        migrations.AddField(
            model_name='rehabcenter',
            name='treatments',
            field=models.JSONField(blank=True, default=list, verbose_name='Treatments'),
        ),
        migrations.AlterField(
            model_name='rehabcenter',
            name='address',
            field=models.TextField(verbose_name='Complete Address'),
        ),
        migrations.AlterField(
            model_name='rehabcenter',
            name='center_facilities',
            field=models.JSONField(blank=True, default=list, verbose_name='Center Facilities'),
        ),
        migrations.AlterField(
            model_name='rehabcenter',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail ID'),
        ),
        migrations.AlterField(
            model_name='rehabcenter',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Experience (Years)'),
        ),
        migrations.AlterField(
            model_name='rehabcenter',
            name='in_room_facilities',
            field=models.JSONField(blank=True, default=list, verbose_name='In-Room Facilities'),
        ),
        migrations.AlterField(
            model_name='rehabcenter',
            name='languages',
            field=models.JSONField(blank=True, default=list, verbose_name='Languages'),
        ),
        migrations.AlterField(
            model_name='rehabcenter',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name of the Centre'),
        ),
        migrations.AlterField(
            model_name='rehabcenter',
            name='patient_profiles',
            field=models.JSONField(blank=True, default=list, verbose_name='Patient Profile'),
        ),
        migrations.AlterField(
            model_name='rehabcenter',
            name='price_range',
            field=models.CharField(blank=True, choices=[('lt2', 'Less than 2 Lakhs'), ('2to3', '2-3 Lakhs'), ('3to4', '3-4 Lakhs'), ('4to5', '4-5 Lakhs'), ('gt5', '5+ Lakhs')], max_length=10, verbose_name='Price Per Month'),
        ),
        migrations.AlterField(
            model_name='rehabcenter',
            name='state',
            field=models.CharField(max_length=100, verbose_name='State Name'),
        ),
        migrations.AlterField(
            model_name='rehabcenter',
            name='videos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='rehabcenterteammember',
            name='qualification',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='rehabcenterteammember',
            name='role',
            field=models.CharField(max_length=255),
        ),
    ]
