# Generated by Django 6.1 on 2026-09-11 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_remove_rehabcenter_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rehabcenter',
            options={},
        ),
    ]
